//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Controller1 : Neo.ApplicationFramework.Tools.OpcClient.DataSourceContainer
	{
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem1;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem2;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem3;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem4;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem5;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem6;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem7;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem8;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem9;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem10;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem11;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem12;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem13;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem14;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem15;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem16;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem17;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem18;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem19;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem20;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem21;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem22;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem23;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem24;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem25;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem26;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem27;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem28;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem29;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem30;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem31;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem32;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem33;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem34;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem35;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem36;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem37;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem38;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem39;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem40;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem41;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem42;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem43;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem44;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem45;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem46;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem47;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem48;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem49;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem50;
		
		public Controller1()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.DataItem1 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem1", "400000.8", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem2 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem2", "400000.9", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem3 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem3", "40030", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem4 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem4", "40032", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem5 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem5", "40034", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem6 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem6", "40036", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem7 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem7", "40038", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem8 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem8", "40040", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem9 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem9", "40042", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem10 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem10", "400000.10", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem11 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem11", "400000.11", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem12 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem12", "400000.12", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem13 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem13", "400000.13", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem14 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem14", "400000.14", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem15 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem15", "40044", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem16 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem16", "40046", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem17 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem17", "40048", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem18 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem18", "40050", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem19 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem19", "40052", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem20 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem20", "400000.15", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem21 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem21", "40054", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem22 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem22", "400000.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem23 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem23", "400000.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem24 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem24", "400000.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem25 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem25", "400000.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem26 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem26", "40056", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem27 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem27", "40058", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem28 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem28", "40060", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem29 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem29", "40062", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem30 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem30", "400000.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem31 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem31", "40064", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem32 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem32", "40066", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem33 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem33", "40068", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem34 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem34", "40070", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem35 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem35", "40072", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem36 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem36", "400000.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem37 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem37", "400000.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem38 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem38", "400000.7", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem39 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem39", "400001.8", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem40 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem40", "400001.9", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem41 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem41", "400001.10", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem42 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem42", "40074", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem43 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem43", "40076", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem44 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem44", "40078", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem45 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem45", "40080", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem46 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem46", "40082", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem47 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem47", "40084", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem48 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem48", "40086", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem49 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem49", "40088", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem50 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem50", "400001.11", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem8)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem10)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem11)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem12)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem13)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem14)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem15)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem16)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem17)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem18)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem19)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem20)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem21)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem22)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem23)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem24)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem25)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem26)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem27)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem28)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem29)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem30)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem31)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem32)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem33)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem34)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem35)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem36)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem37)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem38)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem39)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem40)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem41)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem42)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem43)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem44)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem45)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem46)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem47)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem48)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem49)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem50)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.DataItem1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem8)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem10)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem11)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem12)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem13)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem14)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem15)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem16)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem17)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem18)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem19)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem20)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem21)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem22)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem23)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem24)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem25)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem26)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem27)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem28)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem29)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem30)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem31)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem32)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem33)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem34)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem35)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem36)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem37)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem38)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem39)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem40)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem41)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem42)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem43)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem44)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem45)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem46)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem47)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem48)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem49)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem50)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataItems.Add(this.DataItem1);
			this.DataItems.Add(this.DataItem2);
			this.DataItems.Add(this.DataItem3);
			this.DataItems.Add(this.DataItem4);
			this.DataItems.Add(this.DataItem5);
			this.DataItems.Add(this.DataItem6);
			this.DataItems.Add(this.DataItem7);
			this.DataItems.Add(this.DataItem8);
			this.DataItems.Add(this.DataItem9);
			this.DataItems.Add(this.DataItem10);
			this.DataItems.Add(this.DataItem11);
			this.DataItems.Add(this.DataItem12);
			this.DataItems.Add(this.DataItem13);
			this.DataItems.Add(this.DataItem14);
			this.DataItems.Add(this.DataItem15);
			this.DataItems.Add(this.DataItem16);
			this.DataItems.Add(this.DataItem17);
			this.DataItems.Add(this.DataItem18);
			this.DataItems.Add(this.DataItem19);
			this.DataItems.Add(this.DataItem20);
			this.DataItems.Add(this.DataItem21);
			this.DataItems.Add(this.DataItem22);
			this.DataItems.Add(this.DataItem23);
			this.DataItems.Add(this.DataItem24);
			this.DataItems.Add(this.DataItem25);
			this.DataItems.Add(this.DataItem26);
			this.DataItems.Add(this.DataItem27);
			this.DataItems.Add(this.DataItem28);
			this.DataItems.Add(this.DataItem29);
			this.DataItems.Add(this.DataItem30);
			this.DataItems.Add(this.DataItem31);
			this.DataItems.Add(this.DataItem32);
			this.DataItems.Add(this.DataItem33);
			this.DataItems.Add(this.DataItem34);
			this.DataItems.Add(this.DataItem35);
			this.DataItems.Add(this.DataItem36);
			this.DataItems.Add(this.DataItem37);
			this.DataItems.Add(this.DataItem38);
			this.DataItems.Add(this.DataItem39);
			this.DataItems.Add(this.DataItem40);
			this.DataItems.Add(this.DataItem41);
			this.DataItems.Add(this.DataItem42);
			this.DataItems.Add(this.DataItem43);
			this.DataItems.Add(this.DataItem44);
			this.DataItems.Add(this.DataItem45);
			this.DataItems.Add(this.DataItem46);
			this.DataItems.Add(this.DataItem47);
			this.DataItems.Add(this.DataItem48);
			this.DataItems.Add(this.DataItem49);
			this.DataItems.Add(this.DataItem50);
			this.Driver = "Modicon_Modbus_RTU_ASCII_Pre2.Modicon_Modbus_RTU_ASCII_Pre2.1";
			this.Node = "";
			this.Servername = "Beijer.InprocessNeo.1";
			this.TargetInfoString = "iXDeveloper;WinCe6;Beijer;Exter iX;X2 base 7;en;";
			this.Url = "";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Controller1));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
