//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class SAFLIK_GRAFIGI : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private Neo.ApplicationFramework.Controls.Trend.TrendViewerCF m_TrendViewer;
        
        private bool m_Initialized_SAFLIK_GRAFIGI;
        
        public SAFLIK_GRAFIGI() {
            this.InitializeComponent();
            this.m_Picture.MouseDown += new System.EventHandler(this.m_Picture_Action_MouseDown);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        public Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase TrendViewer {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase>(this.m_TrendViewer);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Controls.Trend.CurveCF curvecf1 = new Neo.ApplicationFramework.Controls.Trend.CurveCF();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_TrendViewer = new Neo.ApplicationFramework.Controls.Trend.TrendViewerCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TrendViewer)).BeginInit();
            this.SuspendLayout();
            // 
            // SAFLIK_GRAFIGI
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.DelayMouseInputPeriod = 0;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 71;
            this.m_Picture.Left = 316;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "SAFLIK_GRAFIGI";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "1074100_612878878863480_419287768912462570_o";
            this.m_Picture.Top = 404;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 181;
            // 
            // m_TrendViewer
            // 
            this.m_TrendViewer.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(67)))), ((int)(((byte)(67))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.BlinkDynamicsValue = false;
            curvecf1.BlinkDynamicsValue = false;
            curvecf1.Color = System.Drawing.Color.Red;
            curvecf1.DataSourceName = "Tags.PSI_OKSIJEN_ORANI";
            curvecf1.DelayMouseInputPeriod = 0;
            curvecf1.DisplayName = "Curve";
            curvecf1.EnabledDynamicsValue = true;
            curvecf1.Height = 307;
            curvecf1.ScreenOwnerName = null;
            curvecf1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Red, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            curvecf1.VisibleDynamicsValue = true;
            curvecf1.Width = 655;
            this.m_TrendViewer.Curves.Add(curvecf1);
            this.m_TrendViewer.DelayMouseInputPeriod = 0;
            this.m_TrendViewer.EnabledDynamicsValue = true;
            this.m_TrendViewer.FontSizePixels = 11;
            this.m_TrendViewer.ForceTransparency = false;
            this.m_TrendViewer.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.GridLineColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.Height = 402;
            this.m_TrendViewer.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(57.010000000000005D, 28.541999999999973D, 57.009999999999991D, 66.48599999999999D);
            this.m_TrendViewer.Left = 15;
            this.m_TrendViewer.Name = "m_TrendViewer";
            this.m_TrendViewer.RequiresTransparency = true;
            this.m_TrendViewer.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.ScreenOwnerName = "SAFLIK_GRAFIGI";
            this.m_TrendViewer.TimeOffset = System.TimeSpan.Parse("00:00:00");
            this.m_TrendViewer.TimeRange = System.TimeSpan.Parse("00:04:00");
            this.m_TrendViewer.TimeScaleMaximum = 39083.5D;
            this.m_TrendViewer.TimeScaleMinimum = 39083.49722222222D;
            this.m_TrendViewer.TimeTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(57.010000000000005D, 344.514D, 57.009999999999991D, 0D);
            this.m_TrendViewer.Top = 9;
            this.m_TrendViewer.Value = 0D;
            this.m_TrendViewer.ValueMajorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(37.010000000000005D, 28.541999999999973D, 721.99D, 66.48599999999999D);
            this.m_TrendViewer.ValueMajorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(721.99D, 28.541999999999973D, 37.009999999999991D, 66.48599999999999D);
            this.m_TrendViewer.ValueMinorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(39.510000000000005D, 28.541999999999973D, 724.49D, 66.48599999999999D);
            this.m_TrendViewer.ValueMinorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(724.49D, 28.541999999999973D, 39.509999999999991D, 66.48599999999999D);
            this.m_TrendViewer.ValueScaleMajorTickCount = 11;
            this.m_TrendViewer.ValueScaleMaximum = 100D;
            this.m_TrendViewer.ValueScaleMinimum = 0D;
            this.m_TrendViewer.ValueScaleMinorTickCount = 4;
            this.m_TrendViewer.ValueTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(15D, 28.541999999999973D, 735.99D, 66.48599999999999D);
            this.m_TrendViewer.ValueTextScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(735.99D, 28.541999999999973D, 15D, 66.48599999999999D);
            this.m_TrendViewer.VisibleDynamicsValue = true;
            this.m_TrendViewer.Width = 769;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "SAFLIK_GRAFIGI";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_SAFLIK_GRAFIGI = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_SAFLIK_GRAFIGI) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Picture);
            this.DrawingPrimitives.Add(this.m_TrendViewer);
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TrendViewer)).EndInit();
        }
        
        private void m_Picture_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture", "MouseDown", "Show Screen", "MENU", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.MENU.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(SAFLIK_GRAFIGI));
            this.m_TrendViewer.Curves[0].DisplayName = resources.GetText("SAFLIK_GRAFIGI.TrendViewer.Curves[0].DisplayName", "Curve");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_SAFLIK_GRAFIGI) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
        }
    }
}
