//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MANUEL;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag OTOMATIK;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag OKSIJEN_TANK_BASINCI;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag PSI_SAG_BASINC;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag PSI_SOL_BASINC;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag PSI_OKSIJEN_ORANI;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag PSA_SAG_KOLON_BASINC_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag PSA_SOL_KOLON_BASINC_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag BEKLEME_TMR;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag BASMA_BOSALTMA1_LOGO;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag BASMA_BOSALTMA2_LOGO;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag DENGELEME_LOGO;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag TANK_DOLUM_1_LOGO;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag TANK_DOLUM_2_LOGO;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag DENGELEME_TMR;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagDateTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag PSA_DONGU_SAYISI;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag SOL_KOLON_DOLDURMA_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag SAG_KOLON_DOLDURMA_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag LIKIT_CALISMA_SURESI_DK;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag LIKIT_BUTON;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag LIKIT_CALISMA_SURESI_SN;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag LIKIT_SEMBOL;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag LOGO_SEMBOL;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag RESET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ALARM_1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ALARM_2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ALARM_3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag DEN1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag CALISMA_SAATI_SIFIRLA;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag CALISMA_SANIYE;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag CALISMA_DAKIKA;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag CALISMA_SAAT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag CALISMA_SAATI_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ALARM_CALISMA_SAATI;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag AKIS_UST;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag AKIS_ALT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag AKIS_BASINC_UST;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag AKIS_BASINC_ALT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag AKIS_DEGERI;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAN_K1_BASMA;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAN_K2_BASMA;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAN_K1_DOLDURMA;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAN_K2_DOLDURMA;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAN_DENGELEME;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MAN_LIKIT_BOSALTMA;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag OTO_BASINC_START_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag OTO_BASINC_STOP_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag O2_SAFLIK_AKIM_UST;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag O2_SAFLIK_AKIM_ALT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag O2_SAFLIK_UST;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag O2_SAFLIK_ALT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag OTO_SAFLIK_UYARI_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag OTO_SAFLIK_STOP_SET;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ALARM_SAFLIK_DUSTU;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.MANUEL = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MANUEL", "Controller1.DataItem1", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.OTOMATIK = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("OTOMATIK", "Controller1.DataItem2", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.OKSIJEN_TANK_BASINCI = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("OKSIJEN_TANK_BASINCI", "Controller1.DataItem3", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.PSI_SAG_BASINC = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("PSI_SAG_BASINC", "Controller1.DataItem4", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.PSI_SOL_BASINC = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("PSI_SOL_BASINC", "Controller1.DataItem5", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.PSI_OKSIJEN_ORANI = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("PSI_OKSIJEN_ORANI", "Controller1.DataItem6", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.PSA_SAG_KOLON_BASINC_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("PSA_SAG_KOLON_BASINC_SET", "Controller1.DataItem7", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.PSA_SOL_KOLON_BASINC_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("PSA_SOL_KOLON_BASINC_SET", "Controller1.DataItem8", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.BEKLEME_TMR = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("BEKLEME_TMR", "Controller1.DataItem9", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.BASMA_BOSALTMA1_LOGO = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("BASMA_BOSALTMA1_LOGO", "Controller1.DataItem10", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.BASMA_BOSALTMA2_LOGO = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("BASMA_BOSALTMA2_LOGO", "Controller1.DataItem11", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.DENGELEME_LOGO = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("DENGELEME_LOGO", "Controller1.DataItem12", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.TANK_DOLUM_1_LOGO = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("TANK_DOLUM_1_LOGO", "Controller1.DataItem13", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.TANK_DOLUM_2_LOGO = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("TANK_DOLUM_2_LOGO", "Controller1.DataItem14", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.DENGELEME_TMR = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("DENGELEME_TMR", "Controller1.DataItem15", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.SystemTagDateTime = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("DateTime", "SystemTagDateTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DATETIME)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DATETIME)), "Current date and time", ((short)(1)), "", "");
			this.PSA_DONGU_SAYISI = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("PSA_DONGU_SAYISI", "Controller1.DataItem16", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.SOL_KOLON_DOLDURMA_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("SOL_KOLON_DOLDURMA_SET", "Controller1.DataItem17", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.SAG_KOLON_DOLDURMA_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("SAG_KOLON_DOLDURMA_SET", "Controller1.DataItem18", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.LIKIT_CALISMA_SURESI_DK = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("LIKIT_CALISMA_SURESI_DK", "Controller1.DataItem19", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.LIKIT_BUTON = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("LIKIT_BUTON", "Controller1.DataItem20", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.LIKIT_CALISMA_SURESI_SN = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("LIKIT_CALISMA_SURESI_SN", "Controller1.DataItem21", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.LIKIT_SEMBOL = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("LIKIT_SEMBOL", "Controller1.DataItem22", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.LOGO_SEMBOL = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("LOGO_SEMBOL", "Controller1.DataItem23", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.RESET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("RESET", "Controller1.DataItem24", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.ALARM_1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ALARM_1", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.ALARM_2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ALARM_2", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.ALARM_3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ALARM_3", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.DEN1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("DEN1", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.CALISMA_SAATI_SIFIRLA = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("CALISMA_SAATI_SIFIRLA", "Controller1.DataItem25", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.CALISMA_SANIYE = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("CALISMA_SANIYE", "Controller1.DataItem26", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.CALISMA_DAKIKA = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("CALISMA_DAKIKA", "Controller1.DataItem27", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.CALISMA_SAAT = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("CALISMA_SAAT", "Controller1.DataItem28", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.CALISMA_SAATI_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("CALISMA_SAATI_SET", "Controller1.DataItem29", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.ALARM_CALISMA_SAATI = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ALARM_CALISMA_SAATI", "Controller1.DataItem30", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.AKIS_UST = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("AKIS_UST", "Controller1.DataItem31", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.AKIS_ALT = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("AKIS_ALT", "Controller1.DataItem32", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.AKIS_BASINC_UST = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("AKIS_BASINC_UST", "Controller1.DataItem33", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.AKIS_BASINC_ALT = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("AKIS_BASINC_ALT", "Controller1.DataItem34", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.AKIS_DEGERI = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("AKIS_DEGERI", "Controller1.DataItem35", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.MAN_K1_BASMA = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAN_K1_BASMA", "Controller1.DataItem36", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MAN_K2_BASMA = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAN_K2_BASMA", "Controller1.DataItem37", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MAN_K1_DOLDURMA = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAN_K1_DOLDURMA", "Controller1.DataItem38", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MAN_K2_DOLDURMA = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAN_K2_DOLDURMA", "Controller1.DataItem39", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MAN_DENGELEME = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAN_DENGELEME", "Controller1.DataItem40", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MAN_LIKIT_BOSALTMA = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MAN_LIKIT_BOSALTMA", "Controller1.DataItem41", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.OTO_BASINC_START_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("OTO_BASINC_START_SET", "Controller1.DataItem42", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.OTO_BASINC_STOP_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("OTO_BASINC_STOP_SET", "Controller1.DataItem43", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.O2_SAFLIK_AKIM_UST = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("O2_SAFLIK_AKIM_UST", "Controller1.DataItem44", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.O2_SAFLIK_AKIM_ALT = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("O2_SAFLIK_AKIM_ALT", "Controller1.DataItem45", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.O2_SAFLIK_UST = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("O2_SAFLIK_UST", "Controller1.DataItem46", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.O2_SAFLIK_ALT = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("O2_SAFLIK_ALT", "Controller1.DataItem47", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.OTO_SAFLIK_UYARI_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("OTO_SAFLIK_UYARI_SET", "Controller1.DataItem48", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.OTO_SAFLIK_STOP_SET = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("OTO_SAFLIK_STOP_SET", "Controller1.DataItem49", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.ALARM_SAFLIK_DUSTU = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ALARM_SAFLIK_DUSTU", "Controller1.DataItem50", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.SystemTagDateTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("31.5.2016 21:07:29"), 0, new string[0], new string[0], true));
			this.LightweightTags.Add(this.MANUEL);
			this.LightweightTags.Add(this.OTOMATIK);
			this.LightweightTags.Add(this.OKSIJEN_TANK_BASINCI);
			this.LightweightTags.Add(this.PSI_SAG_BASINC);
			this.LightweightTags.Add(this.PSI_SOL_BASINC);
			this.LightweightTags.Add(this.PSI_OKSIJEN_ORANI);
			this.LightweightTags.Add(this.PSA_SAG_KOLON_BASINC_SET);
			this.LightweightTags.Add(this.PSA_SOL_KOLON_BASINC_SET);
			this.LightweightTags.Add(this.BEKLEME_TMR);
			this.LightweightTags.Add(this.BASMA_BOSALTMA1_LOGO);
			this.LightweightTags.Add(this.BASMA_BOSALTMA2_LOGO);
			this.LightweightTags.Add(this.DENGELEME_LOGO);
			this.LightweightTags.Add(this.TANK_DOLUM_1_LOGO);
			this.LightweightTags.Add(this.TANK_DOLUM_2_LOGO);
			this.LightweightTags.Add(this.DENGELEME_TMR);
			this.GlobalDataItems.Add(this.SystemTagDateTime);
			this.LightweightTags.Add(this.PSA_DONGU_SAYISI);
			this.LightweightTags.Add(this.SOL_KOLON_DOLDURMA_SET);
			this.LightweightTags.Add(this.SAG_KOLON_DOLDURMA_SET);
			this.LightweightTags.Add(this.LIKIT_CALISMA_SURESI_DK);
			this.LightweightTags.Add(this.LIKIT_BUTON);
			this.LightweightTags.Add(this.LIKIT_CALISMA_SURESI_SN);
			this.LightweightTags.Add(this.LIKIT_SEMBOL);
			this.LightweightTags.Add(this.LOGO_SEMBOL);
			this.LightweightTags.Add(this.RESET);
			this.LightweightTags.Add(this.ALARM_1);
			this.LightweightTags.Add(this.ALARM_2);
			this.LightweightTags.Add(this.ALARM_3);
			this.LightweightTags.Add(this.DEN1);
			this.LightweightTags.Add(this.CALISMA_SAATI_SIFIRLA);
			this.LightweightTags.Add(this.CALISMA_SANIYE);
			this.LightweightTags.Add(this.CALISMA_DAKIKA);
			this.LightweightTags.Add(this.CALISMA_SAAT);
			this.LightweightTags.Add(this.CALISMA_SAATI_SET);
			this.LightweightTags.Add(this.ALARM_CALISMA_SAATI);
			this.LightweightTags.Add(this.AKIS_UST);
			this.LightweightTags.Add(this.AKIS_ALT);
			this.LightweightTags.Add(this.AKIS_BASINC_UST);
			this.LightweightTags.Add(this.AKIS_BASINC_ALT);
			this.LightweightTags.Add(this.AKIS_DEGERI);
			this.LightweightTags.Add(this.MAN_K1_BASMA);
			this.LightweightTags.Add(this.MAN_K2_BASMA);
			this.LightweightTags.Add(this.MAN_K1_DOLDURMA);
			this.LightweightTags.Add(this.MAN_K2_DOLDURMA);
			this.LightweightTags.Add(this.MAN_DENGELEME);
			this.LightweightTags.Add(this.MAN_LIKIT_BOSALTMA);
			this.LightweightTags.Add(this.OTO_BASINC_START_SET);
			this.LightweightTags.Add(this.OTO_BASINC_STOP_SET);
			this.LightweightTags.Add(this.O2_SAFLIK_AKIM_UST);
			this.LightweightTags.Add(this.O2_SAFLIK_AKIM_ALT);
			this.LightweightTags.Add(this.O2_SAFLIK_UST);
			this.LightweightTags.Add(this.O2_SAFLIK_ALT);
			this.LightweightTags.Add(this.OTO_SAFLIK_UYARI_SET);
			this.LightweightTags.Add(this.OTO_SAFLIK_STOP_SET);
			this.LightweightTags.Add(this.ALARM_SAFLIK_DUSTU);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
